# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About Me',  url: 'about-me'}
# - {name: 'Learning Resources', url: 'resources'}
- {name: 'Posts',       url: 'sample-posts'}
# - {name: 'Documentation',      url: 'documentation'}
# - {name: 'ded',              url: 'about'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link:    'https://twitter.com/paululele'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
- {icon: 'instagram', link:  'https://instagram.com/nobullshizpins'}
- {icon: 'envelope', link:   'mailto:shizashaikh456@gmail.com'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share my posts!'

related_posts: 'Other Posts...'

post_date_prefix: 'Written on'
